=== KinsonDigital/kd-admin/schemas/prepare-release-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "ownerName": {
            "type": "string",
            "description": "The owner of the GitHub repository."
        },
        "repoName": {
            "type": "string",
            "description": "The name of the GitHub repository."
        },
        "orgProjectName": {
            "type": "string",
            "description": "The name of the GitHub organization project. This is a V2 project."
        },
        "releaseTypes": {
            "type": "array",
            "description": "The list of release types. Example: preview or production.",
            "items": {
                "$ref": "./release-type-schema.json"
            },
            "minItems": 1
        },
        "githubTokenEnvVarName": {
            "type": "string",
            "description": "The name of the environment variable that contains the GitHub token."
        },
        "versionFilePath": {
            "type": "string",
            "description": "The relative path to the file that contains the version number. Both JSON and csproj files are supported."
        },
        "versionJSONKeyPath": {
            "type": "string",
            "description": "The path to the version number in the JSON file. Only used if the file is a JSON file."
        }
    },
    "required": ["ownerName", "repoName", "releaseTypes", "githubTokenEnvVarName"]
}

=== KinsonDigital/kd-admin/prepare-release-settings.json
{
    "ownerName": "KinsonDigital",
    "repoName": "kd-admin",
    "orgProjectName": "KD-Team",
    "releaseTypes": [{
        "name": "preview",
        "reviewer": "KinsonDigitalAdmin",
        "assignee": "CalvinWilkinson",
        "headBranch": "prev-release",
        "baseBranch": "preview",
        "genReleaseSettingsFilePath": "./gen-release-notes-settings.json",
        "releasePrTemplateFilePath": "./templates/prev-prepare-release-template.md",
        "releaseNotesDirPath": "./release-notes/preview-releases",
        "releaseLabels": ["ðŸš€Preview Release"],
        "prTitle": "ðŸš€Preview Release - ${VERSION}"
    },
    {
        "name": "production",
        "reviewer": "KinsonDigitalAdmin",
        "assignee": "CalvinWilkinson",
        "headBranch": "prod-release",
        "baseBranch": "main",
        "genReleaseSettingsFilePath": "./gen-release-notes-settings.json",
        "releasePrTemplateFilePath": "./templates/prod-prepare-release-template.md",
        "releaseNotesDirPath": "./release-notes/production-releases",
        "releaseLabels": ["ðŸš€Production Release"],
        "prTitle": "ðŸš€Production Release - ${VERSION}"
    }],
    "githubTokenEnvVarName": "CICD_TOKEN"
}

=== KinsonDigital/kd-admin/dev-tools/prepare-release-settings.json
{
  "ownerName": "",
  "repoName": "",
  "orgProjectName": "",
  "releaseTypes": [
    {
      "name": "",
      "reviewer": "",
      "assignee": "",
      "headBranch": "",
      "baseBranch": "",
      "genReleaseSettingsFilePath": "",
      "releaseNotesDirPath": "",
      "releasePrTemplateFilePath": "",
      "releaseLabels": [],
      "prTitle": ""
    }
  ],
  "githubTokenEnvVarName": "",
  "versionFilePath": ""
}
